Fixed Invoice generation
aravin25/cms pull request #41
Opened 2024-03-08 05:43 UTC by SurajDs-git

2024-03-08 09:04 UTC, jerinjtitus requested changes

2024-03-11 05:01 UTC, GopeshMv commented on src/main/java/org/odyssey/cms/service/CustomerServiceImpl.java
>  		} else if (optionalMerchant.isEmpty()) {
Completed

2024-03-11 05:04 UTC, GopeshMv requested changes

2024-03-11 05:04 UTC, GopeshMv commented on src/main/resources/application.properties
Remove the credentials

2024-03-11 05:17 UTC, SurajDs-git commented on src/main/resources/application.properties
Done

2024-03-11 07:11 UTC, merged